language: python
cache: false
python:
  - '3.8'

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y -v --default-toolchain nightly
  - source $HOME/.cargo/env

install:
  - pip install pipenv
  - pipenv install --skip-lock
  - pip install -e . -U
script:
  - py.test
  - cargo test
  - black --check
